# -*- coding: utf-8 -*-
"""WealthScraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOn1wtz6yEmfVXNji0czDYo4U6VpLqx4
"""

from __future__ import annotations

import pdfplumber
import re
import json
import csv
import argparse
from pathlib import Path
from dataclasses import dataclass, field, asdict
from collections import defaultdict


# ── Data Models ──────────────────────────────────────────────

@dataclass
class Transaction:
    date: str
    description: str
    amount: float
    transaction_type: str   # debit / credit
    category: str
    sub_category: str = ""
    raw_description: str = ""


@dataclass
class FinancialSummary:
    account_holder: str = ""
    account_number: str = ""
    bank_name: str = ""
    statement_period_start: str = ""
    statement_period_end: str = ""
    opening_balance: float = 0.0
    closing_balance: float = 0.0
    total_income: float = 0.0
    salary_income: float = 0.0
    other_income: float = 0.0
    total_expenses: float = 0.0
    essential_expenses: float = 0.0
    discretionary_expenses: float = 0.0
    total_investments: float = 0.0
    mutual_funds: float = 0.0
    stocks: float = 0.0
    fd_rd: float = 0.0
    insurance_premiums: float = 0.0
    total_liabilities: float = 0.0
    loan_emis: float = 0.0
    credit_card_payments: float = 0.0
    liquid_assets: float = 0.0
    savings_rate: float = 0.0
    investment_rate: float = 0.0
    debt_to_income_ratio: float = 0.0
    transactions: list = field(default_factory=list)
    # Aggregates for easy "bifurcation" queries (also exported to JSON)
    debit_by_sub_category: dict = field(default_factory=dict)
    credit_by_sub_category: dict = field(default_factory=dict)
    debit_by_category: dict = field(default_factory=dict)
    credit_by_category: dict = field(default_factory=dict)


# ── Category Rules ───────────────────────────────────────────

CATEGORY_RULES = {
    # Income
    "salary":         ("income",     "salary"),
    "payroll":        ("income",     "salary"),
    "stipend":        ("income",     "salary"),
    "pension":        ("income",     "salary"),
    "dividend":       ("income",     "dividend"),
    "intpd":          ("income",     "interest"),
    "interest":       ("income",     "interest"),
    "refund":         ("income",     "refund"),
    "cashback":       ("income",     "cashback"),
    "bhimcashba":     ("income",     "cashback"),
    "nidhi":          ("income",     "transfer_in"),   # seen in Dhruv's SBI

    # Investments
    "sip":            ("investment", "mutual_fund"),
    "mutualfund":     ("investment", "mutual_fund"),
    "zerodha":        ("investment", "stocks"),
    "groww":          ("investment", "stocks"),
    "upstox":         ("investment", "stocks"),
    "fixeddeposit":   ("investment", "fd_rd"),
    "lic":            ("investment", "insurance"),
    "insurance":      ("investment", "insurance"),
    "ppf":            ("investment", "ppf"),
    "nps":            ("investment", "nps"),
    "apy":            ("investment", "nps"),
    "epf":            ("investment", "pf"),

    # Liabilities
    "emi":            ("liability",  "loan_emi"),
    "loanrepay":      ("liability",  "loan_emi"),
    "creditcard":     ("liability",  "credit_card"),
    "amcatmcrd":      ("liability",  "bank_charges"),
    "amccharges":     ("liability",  "bank_charges"),

    # Food & Dining
    "swiggy":         ("expense",    "dining"),
    "zomato":         ("expense",    "dining"),
    "zaikamo":        ("expense",    "dining"),
    "topburger":      ("expense",    "dining"),
    "mcdonalds":      ("expense",    "dining"),
    "mcdonald":       ("expense",    "dining"),
    "dominos":        ("expense",    "dining"),
    "kfc":            ("expense",    "dining"),

    # Groceries
    "blinkit":        ("expense",    "groceries"),
    "bigbasket":      ("expense",    "groceries"),
    "jiomart":        ("expense",    "groceries"),
    "relianceretai":  ("expense",    "groceries"),
    "dmart":          ("expense",    "groceries"),

    # Transport
    "uber":           ("expense",    "transport"),
    "rapido":         ("expense",    "transport"),
    "zoomcar":        ("expense",    "transport"),
    "petrol":         ("expense",    "transport"),
    "fuel":           ("expense",    "transport"),
    "cab":            ("expense",    "transport"),

    # Travel
    "irctc":          ("expense",    "travel"),
    "irctcweb":       ("expense",    "travel"),
    "irctctourism":   ("expense",    "travel"),
    "flight":         ("expense",    "travel"),
    "makemytrip":     ("expense",    "travel"),
    "goibibo":        ("expense",    "travel"),

    # Shopping
    "amazon":         ("expense",    "shopping"),
    "amazonpay":      ("expense",    "shopping"),
    "amzn":           ("expense",    "shopping"),
    "flipkart":       ("expense",    "shopping"),
    "decathlon":      ("expense",    "shopping"),
    "decathl":        ("expense",    "shopping"),
    "myntra":         ("expense",    "shopping"),
    "meesho":         ("expense",    "shopping"),
    "nykaa":          ("expense",    "shopping"),
    "ajio":           ("expense",    "shopping"),
    "tatacliq":       ("expense",    "shopping"),

    # Entertainment / Subscriptions
    "netflix":        ("expense",    "entertainment"),
    "spotify":        ("expense",    "entertainment"),
    "hotstar":        ("expense",    "entertainment"),
    "prime":          ("expense",    "entertainment"),
    "amazonprime":    ("expense",    "entertainment"),
    "openaillc":      ("expense",    "subscriptions"),
    "openai":         ("expense",    "subscriptions"),
    "hubble":         ("expense",    "subscriptions"),   # Hubble wallet/app
    "vortexgaming":   ("expense",    "gaming"),

    # Telecom / Utilities
    "airtel":         ("expense",    "utilities"),
    "wwwairt":        ("expense",    "utilities"),
    "jiopostpaid":    ("expense",    "utilities"),
    "jiomobile":      ("expense",    "utilities"),
    "jio":            ("expense",    "utilities"),
    "vi":             ("expense",    "utilities"),
    "vodafone":       ("expense",    "utilities"),
    "idea":           ("expense",    "utilities"),
    "broadband":      ("expense",    "utilities"),
    "electricity":    ("expense",    "utilities"),
    "bescom":         ("expense",    "utilities"),
    "water":          ("expense",    "utilities"),
    "gas":            ("expense",    "utilities"),

    # Education
    "jaypeeinstitu":  ("expense",    "education"),
    "jaypeei":        ("expense",    "education"),
    "school":         ("expense",    "education"),
    "tuition":        ("expense",    "education"),
    "college":        ("expense",    "education"),
    "fees":           ("expense",    "education"),

    # Medical
    "pharmacy":       ("expense",    "medical"),
    "hospital":       ("expense",    "medical"),
    "apollo":         ("expense",    "medical"),
    "medical":        ("expense",    "medical"),
    "1mg":            ("expense",    "medical"),
    "pharmeasy":      ("expense",    "medical"),

    # POS / ATM
    "posprcr":        ("expense",    "pos_purchase"),
    "atm":            ("expense",    "cash_withdrawal"),
    "debitcard":      ("expense",    "pos_purchase"),
    "pos":            ("expense",    "pos_purchase"),

    # Transfers (kept under "other" to not inflate expenses)
    "imps":           ("other",      "transfer"),
    "neft":           ("other",      "transfer"),
    "rtgs":           ("other",      "transfer"),
    "upi":            ("other",      "transfer"),
}

ESSENTIAL_SUBCATEGORIES = {
    "groceries", "medical", "education", "utilities", "transport"
}

SUBCATEGORY_LABELS = {
    "dining": "Food & Dining",
    "groceries": "Groceries",
    "transport": "Transport",
    "travel": "Travel",
    "shopping": "Shopping",
    "entertainment": "Entertainment",
    "subscriptions": "Subscriptions",
    "gaming": "Gaming",
    "utilities": "Utilities",
    "education": "Education",
    "medical": "Medical",
    "cash_withdrawal": "Cash Withdrawal",
    "pos_purchase": "POS Purchase",
    "mutual_fund": "Mutual Funds",
    "stocks": "Stocks",
    "fd_rd": "Fixed/Recurring Deposits",
    "insurance": "Insurance",
    "loan_emi": "Loan EMI",
    "credit_card": "Credit Card Payment",
    "bank_charges": "Bank Charges",
    "transfer_in": "Transfer In",
    "interest": "Interest",
    "refund": "Refund",
    "cashback": "Cashback",
    "uncategorized": "Uncategorized",
}


# ── Main Scraper ─────────────────────────────────────────────

class BankStatementScraper:

    def __init__(self, pdf_path: str, password: str = ""):
        self.pdf_path    = Path(pdf_path)
        self.password    = password
        self.raw_text    = ""
        self.bank_format = "unknown"   # "sbi" or "uco"
        self.summary     = FinancialSummary()

    # ── Step 1: Extract text (password aware) ────────────────
    def extract_raw_data(self):
        try:
            with pdfplumber.open(self.pdf_path, password=self.password) as pdf:
                for page in pdf.pages:
                    text = page.extract_text()
                    if text:
                        self.raw_text += text + "\n"
            print(f"  Text extracted ({len(self.raw_text)} chars)")

        except Exception:
            print("PDF is password protected.")
            print("""
Common bank statement passwords:
- Most banks  -> DDMMYYYY (date of birth)  e.g. 15081999
- SBI         -> First 5 letters of name + DOB  e.g. DHRUV23112005
- ICICI       -> First 4 letters of name + DOB  e.g. DHRU23112005
- UCO Bank    -> DDMMYYYY
""")
            unlocked = False
            for attempt in range(3):
                pwd = input(f"  Enter password (attempt {attempt+1}/3): ").strip()
                try:
                    with pdfplumber.open(self.pdf_path, password=pwd) as pdf:
                        for page in pdf.pages:
                            text = page.extract_text()
                            if text:
                                self.raw_text += text + "\n"
                    print(f"  Unlocked. ({len(self.raw_text)} chars extracted)")
                    unlocked = True
                    break
                except Exception:
                    print("  Wrong password, try again.")

            if not unlocked:
                raise ValueError(
                    "Could not unlock PDF.\n"
                    "Tip: Open PDF -> Print -> Save as PDF to remove password, then re-upload."
                )

    # ── Step 2: Detect bank format ───────────────────────────
    def detect_bank(self):
        text_upper = self.raw_text.upper()
        # Order matters: UCO statements often contain 'SBIN' in UPI refs,
        # so check for UCO Bank before SBI and only treat as SBI when clearly present.
        if "UCO BANK" in text_upper or "STATEMENT FOR ACCOUNT NUMBER" in text_upper and "UCO" in text_upper:
            self.bank_format = "uco"
            self.summary.bank_name = "UCO Bank"
        elif "STATE BANK OF INDIA" in text_upper:
            self.bank_format = "sbi"
            self.summary.bank_name = "State Bank of India"
        elif "HDFC" in text_upper:
            self.bank_format = "hdfc"
            self.summary.bank_name = "HDFC Bank"
        elif "ICICI" in text_upper:
            self.bank_format = "icici"
            self.summary.bank_name = "ICICI Bank"
        else:
            self.bank_format = "generic"
            self.summary.bank_name = "Unknown Bank"
        print(f"  Detected bank format: {self.bank_format.upper()}")

    # ── Step 3: Parse metadata ───────────────────────────────
    def parse_metadata(self):
        text = self.raw_text

        if self.bank_format == "sbi":
            self._parse_metadata_sbi(text)
        elif self.bank_format == "uco":
            self._parse_metadata_uco(text)
        else:
            self._parse_metadata_generic(text)

    def _parse_metadata_sbi(self, text):
        # Name: "Welcome: As on DD-MM-YYYY  NAME"
        name_m = re.search(r"Welcome:.*?(\d{2}-\d{2}-\d{4})\s+([A-Z][A-Z\s]{3,40})", text)
        if name_m:
            self.summary.account_holder = name_m.group(2).strip()

        # Account number
        acc_m = re.search(r"Account Number\s*:\s*(\d{10,18})", text, re.IGNORECASE)
        if acc_m:
            self.summary.account_number = acc_m.group(1)

        # Statement period: "Statement From :01-01-2026 to 31-01-2026"
        period_m = re.search(
            r"Statement From\s*:\s*(\d{2}-\d{2}-\d{4})\s+to\s+(\d{2}-\d{2}-\d{4})",
            text, re.IGNORECASE
        )
        if period_m:
            self.summary.statement_period_start = period_m.group(1)
            self.summary.statement_period_end   = period_m.group(2)

        # Opening balance = balance before first transaction
        # In SBI format, balance appears after the last amount on each line
        # The first balance value after header is opening
        balances = re.findall(r"([\d,]+\.\d{2})(?:CR|DR)?", text)
        # Clear Balance shown in header
        clear_bal = re.search(r"Clear Balance\s*:\s*([\d,]+\.\d{2})", text, re.IGNORECASE)
        if clear_bal:
            self.summary.closing_balance = self._to_float(clear_bal.group(1))

    def _parse_metadata_uco(self, text):
        acc_m = re.search(r"account number\s+(\d{10,18})", text, re.IGNORECASE)
        if acc_m:
            self.summary.account_number = acc_m.group(1)

        period_m = re.search(
            r"Between\s+(\d{2}-\d{2}-\d{4})\s+and\s+(\d{2}-\d{2}-\d{4})",
            text, re.IGNORECASE
        )
        if period_m:
            self.summary.statement_period_start = period_m.group(1)
            self.summary.statement_period_end   = period_m.group(2)

        name_m = re.search(r"^Name\s+([A-Z]+(?:\s+[A-Z]+){1,4})", text, re.MULTILINE)
        if name_m:
            bad = {"UCO","BANK","KENDRIYA","VIDYALAY","KOTA","SCHOOL","GALI","NAGAR","BEHIND"}
            words = [w for w in name_m.group(1).split()
                     if w not in bad]
            if words:
                self.summary.account_holder = " ".join(words)

        ob = re.search(r"Opening Balance\s+([\d.]+)", text)
        cb = re.search(r"Closing Balance\s+([\d.]+)", text)
        if ob:
            self.summary.opening_balance = self._to_float(ob.group(1))
        if cb:
            self.summary.closing_balance = self._to_float(cb.group(1))

    def _parse_metadata_generic(self, text):
        acc_m = re.search(r"(?:Account\s*(?:No|Number))[:\s]+(\d{8,18})", text, re.IGNORECASE)
        if acc_m:
            self.summary.account_number = acc_m.group(1)

    # ── Step 4: Parse transactions ───────────────────────────
    def parse_transactions(self):
        if self.bank_format == "sbi":
            self._parse_sbi()
        elif self.bank_format == "uco":
            self._parse_uco()
        else:
            self._parse_uco()  # fallback

        print(f"  Parsed {len(self.summary.transactions)} transactions")

    # ── SBI Parser ───────────────────────────────────────────
    def _parse_sbi(self):
        """
        SBI actual format (WDL/DEP on its own line, data on next line):

        Line N:   'WDL TFR'   or   'DEP TFR'
        Line N+1: 'DD/MM/YYYY DD/MM/YYYY UPI/DR/.../MERCHANT - AMT - BAL'
        Line N+2: '/BANK/handle/...'   (continuation, optional)
        Line N+3: 'REF AT BRANCH'      (ref, skip)
        """
        DATA_RE = re.compile(
            r"^(\d{2}/\d{2}/\d{4})\s+"    # date1
            r"\d{2}/\d{2}/\d{4}\s+"        # date2 (duplicate)
            r"(.+?)\s+"                        # description (lazy)
            r"-\s+"                            # dash separator
            r"([\d,]+\.\d{2}|-)\s+"        # withdrawal or -
            r"-?\s*"                           # optional dash
            r"([\d,]+\.\d{2}|-)\s+"        # deposit or -
            r"([\d,]+\.\d{2})"              # running balance
        )

        lines = self.raw_text.split("\n")
        balances_seen = []
        current_type = None

        for i, line in enumerate(lines):
            stripped = line.strip()

            # Detect WDL/DEP marker line
            if stripped.startswith("WDL"):
                current_type = "debit"
                continue
            if stripped.startswith("DEP"):
                current_type = "credit"
                continue

            # Try to match data line
            m = DATA_RE.match(stripped)
            if not m or current_type is None:
                continue

            date     = m.group(1)
            raw_desc = m.group(2).strip()
            wdl      = m.group(3)
            dep      = m.group(4)
            balance  = self._to_float(m.group(5))

            # Collect continuation line (next line starting with /)
            continuation = ""
            if i + 1 < len(lines):
                nxt = lines[i + 1].strip()
                if nxt.startswith("/"):
                    continuation = nxt

            full_desc = raw_desc + continuation

            merchant = self._extract_merchant(full_desc) or raw_desc[:60]

            # Get amount (whichever is not "-")
            amount = self._to_float(wdl if wdl != "-" else dep)

            # Compute opening balance from first transaction
            if not balances_seen:
                if current_type == "debit":
                    self.summary.opening_balance = round(balance + amount, 2)
                else:
                    self.summary.opening_balance = round(balance - amount, 2)
            balances_seen.append(balance)

            category, sub_cat = self._categorize(merchant + " " + full_desc)
            # If we couldn't classify but it looks like a transfer, label it as such
            if category == "other" and sub_cat == "uncategorized":
                if re.search(r"\bUPI/|IMPS/|NEFT/|RTGS/|ACH/|NACH\b", full_desc, re.IGNORECASE):
                    sub_cat = "transfer"

            self.summary.transactions.append(Transaction(
                date=date,
                description=merchant,
                raw_description=full_desc,
                amount=amount,
                transaction_type=current_type,
                category=category,
                sub_category=sub_cat
            ))

            current_type = None  # reset after consuming data line

        if balances_seen:
            self.summary.closing_balance = balances_seen[-1]

    def _clean_sbi_desc(self, desc: str, full_line: str) -> str:
        """
        Extract merchant name from SBI UPI description.
        UPI/DR/600130602066/Mr ANIL/YESB/q702618131/UPI → Mr ANIL
        UPI/CR/696696487260/NIDHI GA/PUNB/9828858006/Sent → NIDHI GA
        """
        # Try extracting after 3rd slash in UPI ref
        upi_m = re.search(r"UPI/(?:DR|CR)/\d+/([^/]+)", desc, re.IGNORECASE)
        if upi_m:
            name = upi_m.group(1).strip()
            # Remove trailing junk
            name = re.sub(r'\s+\w{4,}\s*$', '', name).strip()
            return name

        # NEFT/IMPS pattern
        neft_m = re.search(r"(?:NEFT|IMFT|IMPS)/\w+/(.+?)(?:/|$)", desc, re.IGNORECASE)
        if neft_m:
            return neft_m.group(1).strip()

        return desc[:60].strip()

    def _extract_merchant(self, full_desc: str) -> str:
        """
        Try to extract a human-readable merchant/person from raw narration.
        Works best for SBI UPI strings, but also handles NEFT/IMPS/POS-ish texts.
        """
        desc = (full_desc or "").strip()
        if not desc:
            return ""

        # UPI patterns
        upi_m = re.search(r"UPI/(?:DR|CR)/\d+/([^/]+)", desc, re.IGNORECASE)
        if upi_m:
            name = upi_m.group(1).strip()
            name = re.sub(r"\s+\w{4,}\s*$", "", name).strip()
            return name[:60]

        # NEFT/IMPS/RTGS patterns: NEFT/XXXX/NAME/...
        bank_m = re.search(r"(?:NEFT|IMFT|IMPS|RTGS)/[^/]+/([^/]+)", desc, re.IGNORECASE)
        if bank_m:
            return bank_m.group(1).strip()[:60]

        # POS / card purchase hints
        pos_m = re.search(r"\bPOS(?:\s*PRCR)?\s+([A-Z0-9][A-Z0-9\s\-]{2,40})", desc, re.IGNORECASE)
        if pos_m:
            return pos_m.group(1).strip()[:60]

        # Fallback: first chunk before amount separators
        return re.split(r"\s+-\s+", desc, maxsplit=1)[0].strip()[:60]

    # ── UCO Parser ───────────────────────────────────────────
    def _parse_uco(self):
        """
        UCO Bank: plain text, 3-line blocks:
        MPAYUPITRTR...MERCHANTNAME...
        DD-Mon-YYYY  amount  balance
        ref/timestamp
        """
        txn_re = re.compile(
            r"^(\d{2}-(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-\d{4})"
            r"\s+([\d]+(?:\.\d+)?)"
            r"\s+([\d]+\.\d{2})"
            r"\s*$",
            re.MULTILINE | re.IGNORECASE
        )

        lines = self.raw_text.split("\n")
        prev_balance = self.summary.opening_balance

        for i, line in enumerate(lines):
            m = txn_re.match(line.strip())
            if not m:
                continue

            date    = m.group(1)
            amount  = self._to_float(m.group(2))
            balance = self._to_float(m.group(3))

            txn_type = "credit" if round(balance, 2) > round(prev_balance, 2) else "debit"

            # Description = line above (skip ref ID lines)
            particulars = ""
            if i > 0:
                above = lines[i - 1].strip()
                if re.match(r"^[\d/\-:\s]+$", above):
                    above = lines[i - 2].strip() if i > 1 else ""
                particulars = above

            cleaned_particulars = self._clean_particulars(particulars)
            category, sub_cat = self._categorize(cleaned_particulars)
            if category == "other" and sub_cat == "uncategorized":
                if re.search(r"\bUPI\b|IMPS|NEFT|RTGS|ACH|NACH", particulars, re.IGNORECASE):
                    sub_cat = "transfer"
            self.summary.transactions.append(Transaction(
                date=date,
                description=cleaned_particulars,
                raw_description=particulars,
                amount=amount,
                transaction_type=txn_type,
                category=category,
                sub_category=sub_cat
            ))
            prev_balance = balance

    # ── Categorize ───────────────────────────────────────────
    def _categorize(self, description: str) -> tuple:
        desc = self._normalize_for_rules(description)
        for keyword, (cat, sub) in CATEGORY_RULES.items():
            if self._normalize_for_rules(keyword) in desc:
                return cat, sub
        # Heuristic fallbacks (helps a lot for generic PDFs)
        if "atm" in desc or "cashwithdraw" in desc:
            return "expense", "cash_withdrawal"
        if "pos" in desc or "debitcard" in desc:
            return "expense", "pos_purchase"
        return "other", "uncategorized"

    def _normalize_for_rules(self, s: str) -> str:
        # Lowercase and keep only alphanumerics to match messy narration reliably
        return re.sub(r"[^a-z0-9]+", "", (s or "").lower())

    def _clean_particulars(self, s: str) -> str:
        """
        Strip noisy prefixes so categorization sees the merchant clearly.
        """
        text = (s or "").strip()
        # remove common UCO/UPI prefixes
        text = re.sub(r"^(MPAYUPITRTR|MPAYUPI|UPI|IMPS|NEFT|RTGS)\s*", "", text, flags=re.IGNORECASE)
        # remove long ref-like blobs
        text = re.sub(r"\b\d{10,}\b", "", text).strip()
        return re.sub(r"\s{2,}", " ", text).strip()

    # ── Aggregate ────────────────────────────────────────────
    def compute_summary(self):
        debit_by_sub = defaultdict(float)
        credit_by_sub = defaultdict(float)
        debit_by_cat = defaultdict(float)
        credit_by_cat = defaultdict(float)

        for txn in self.summary.transactions:
            if txn.transaction_type == "credit":
                self.summary.liquid_assets += txn.amount
                credit_by_sub[txn.sub_category or "uncategorized"] += txn.amount
                credit_by_cat[txn.category or "uncategorized"] += txn.amount
                if txn.category == "income":
                    self.summary.total_income += txn.amount
                    if txn.sub_category == "salary":
                        self.summary.salary_income += txn.amount
                    else:
                        self.summary.other_income  += txn.amount

            elif txn.transaction_type == "debit":
                debit_by_sub[txn.sub_category or "uncategorized"] += txn.amount
                debit_by_cat[txn.category or "uncategorized"] += txn.amount
                if txn.category == "investment":
                    self.summary.total_investments += txn.amount
                    if   txn.sub_category == "mutual_fund": self.summary.mutual_funds       += txn.amount
                    elif txn.sub_category == "stocks":      self.summary.stocks             += txn.amount
                    elif txn.sub_category == "fd_rd":       self.summary.fd_rd              += txn.amount
                    elif txn.sub_category == "insurance":   self.summary.insurance_premiums += txn.amount

                elif txn.category == "liability":
                    self.summary.total_liabilities += txn.amount
                    if   txn.sub_category == "loan_emi":    self.summary.loan_emis            += txn.amount
                    elif txn.sub_category == "credit_card": self.summary.credit_card_payments += txn.amount

                elif txn.category in ("expense", "other"):
                    self.summary.total_expenses += txn.amount
                    if txn.sub_category in ESSENTIAL_SUBCATEGORIES:
                        self.summary.essential_expenses     += txn.amount
                    else:
                        self.summary.discretionary_expenses += txn.amount

        if self.summary.total_income > 0:
            net = (self.summary.total_income
                   - self.summary.total_expenses
                   - self.summary.total_investments)
            self.summary.savings_rate         = round(net / self.summary.total_income * 100, 2)
            self.summary.investment_rate      = round(self.summary.total_investments / self.summary.total_income * 100, 2)
            self.summary.debt_to_income_ratio = round(self.summary.total_liabilities / self.summary.total_income * 100, 2)

        # Freeze aggregates into plain dicts for JSON export
        self.summary.debit_by_sub_category = dict(sorted(debit_by_sub.items(), key=lambda x: -x[1]))
        self.summary.credit_by_sub_category = dict(sorted(credit_by_sub.items(), key=lambda x: -x[1]))
        self.summary.debit_by_category = dict(sorted(debit_by_cat.items(), key=lambda x: -x[1]))
        self.summary.credit_by_category = dict(sorted(credit_by_cat.items(), key=lambda x: -x[1]))

    def _to_float(self, value: str) -> float:
        try:
            # Remove currency symbols/words and separators (keep decimal dot)
            s = str(value)
            s = s.replace("₹", "").replace("INR", "").replace("Rs.", "").replace("Rs", "")
            cleaned = re.sub(r"[,\s]", "", s)
            return float(cleaned)
        except (ValueError, TypeError):
            return 0.0

    def run(self) -> FinancialSummary:
        print(f"\nProcessing: {self.pdf_path.name}")
        self.extract_raw_data()
        self.detect_bank()
        self.parse_metadata()
        self.parse_transactions()
        self.compute_summary()
        print("Done.\n")
        return self.summary


# ── Report Printer ───────────────────────────────────────────

def print_report(summary: FinancialSummary):
    sep = "=" * 56
    print(sep)
    print("          BANK STATEMENT ANALYSIS REPORT")
    print(sep)
    print(f"  Account Holder  : {summary.account_holder or 'N/A'}")
    print(f"  Bank            : {summary.bank_name or 'N/A'}")
    print(f"  Account No.     : {summary.account_number or 'N/A'}")
    print(f"  Period          : {summary.statement_period_start} -> {summary.statement_period_end}")
    print(f"  Opening Balance : INR {summary.opening_balance:>12,.2f}")
    print(f"  Closing Balance : INR {summary.closing_balance:>12,.2f}")
    print("-" * 56)
    print(f"  Total Income (Credits)     : INR {summary.total_income:>10,.2f}")
    print(f"     - Salary               : INR {summary.salary_income:>10,.2f}")
    print(f"     - Other                : INR {summary.other_income:>10,.2f}")
    print(f"  Total Expenses (Debits)    : INR {summary.total_expenses:>10,.2f}")
    print(f"     - Essential            : INR {summary.essential_expenses:>10,.2f}")
    print(f"     - Discretionary        : INR {summary.discretionary_expenses:>10,.2f}")
    print(f"  Total Investments          : INR {summary.total_investments:>10,.2f}")
    print(f"     - Mutual Funds         : INR {summary.mutual_funds:>10,.2f}")
    print(f"     - Stocks               : INR {summary.stocks:>10,.2f}")
    print(f"     - FD / RD              : INR {summary.fd_rd:>10,.2f}")
    print(f"     - Insurance/APY        : INR {summary.insurance_premiums:>10,.2f}")
    print(f"  Total Liabilities          : INR {summary.total_liabilities:>10,.2f}")
    print(f"     - Loan EMIs            : INR {summary.loan_emis:>10,.2f}")
    print(f"     - Credit Card          : INR {summary.credit_card_payments:>10,.2f}")
    print("-" * 56)
    print(f"  Savings Rate               : {summary.savings_rate:>8}%")
    print(f"  Investment Rate            : {summary.investment_rate:>8}%")
    print(f"  Debt-to-Income             : {summary.debt_to_income_ratio:>8}%")
    print(f"  Transactions Found         : {len(summary.transactions)}")
    print(sep)


def print_category_breakdown(summary: FinancialSummary, top_n: int | None = None):
    print("\nCREDIT BREAKDOWN (Money received):")
    print("-" * 50)
    credit_items = list((summary.credit_by_sub_category or {}).items())
    if top_n is not None:
        credit_items = credit_items[: max(0, int(top_n))]
    if credit_items:
        for label, total in credit_items:
            pretty = SUBCATEGORY_LABELS.get(label, label.replace("_", " ").title())
            print(f"  {pretty} ({label})".ljust(34) + f"INR {total:>10,.2f}")
    else:
        print("  No credit transactions found.")

    print("\nDEBIT BREAKDOWN (Money spent):")
    print("-" * 50)
    debit_items = list((summary.debit_by_sub_category or {}).items())
    if top_n is not None:
        debit_items = debit_items[: max(0, int(top_n))]
    if debit_items:
        for label, total in debit_items:
            pretty = SUBCATEGORY_LABELS.get(label, label.replace("_", " ").title())
            print(f"  {pretty} ({label})".ljust(34) + f"INR {total:>10,.2f}")
    else:
        print("  No debit transactions found.")


# ── Export ───────────────────────────────────────────────────

def export_json(summary: FinancialSummary, path: str):
    data = asdict(summary)
    data["transactions"] = [asdict(t) for t in summary.transactions]
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"JSON saved: {path}")

def export_csv(summary: FinancialSummary, path: str):
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "date", "description", "amount",
            "transaction_type", "category", "sub_category",
            "raw_description"
        ])
        writer.writeheader()
        for txn in summary.transactions:
            writer.writerow(asdict(txn))
    print(f"CSV saved: {path}")


def main():
    parser = argparse.ArgumentParser(
        prog="wealthscraper",
        description="Parse a bank statement PDF and generate JSON/CSV summaries.",
    )
    parser.add_argument("pdf", help="Path to the bank statement PDF")
    parser.add_argument(
        "--password",
        default="",
        help="PDF password (if protected). If omitted, you will be prompted (up to 3 tries).",
    )
    parser.add_argument("--out-json", default="financial_summary.json", help="Output JSON path")
    parser.add_argument("--out-csv", default="transactions.csv", help="Output CSV path")
    parser.add_argument(
        "--no-breakdown",
        action="store_true",
        help="Skip printing category breakdown tables",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=None,
        help="Only show top N rows in breakdown tables (optional)",
    )
    parser.add_argument(
        "--debug-dump",
        action="store_true",
        help="Print first 120 lines of extracted text for debugging parsing issues",
    )
    args = parser.parse_args()

    pdf_path = Path(args.pdf)
    if not pdf_path.exists():
        raise FileNotFoundError(f"PDF not found: {pdf_path}")

    scraper = BankStatementScraper(str(pdf_path), password=args.password)
    summary = scraper.run()

    if args.debug_dump:
        print("\n--- DEBUG: First 120 lines of extracted text ---")
        for i, line in enumerate(scraper.raw_text.split("\n")[:120]):
            print(f"{i:3}: {line!r}")
        print("--- END DEBUG ---\n")

    print_report(summary)
    if not args.no_breakdown:
        print_category_breakdown(summary, top_n=args.top)

    export_json(summary, args.out_json)
    export_csv(summary, args.out_csv)


if __name__ == "__main__":
    main()